version: "{build}"

build: off
test: off

branches:
  only:
  - deploy

artifacts:
- path: content
  name: content

before_deploy:
- ps: New-Item content\version.txt -type file -value "$env:APPVEYOR_BUILD_NUMBER`r`n" -force
- ps: $root = Resolve-Path .\content; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName content }

deploy:
- provider: AzureBlob
  storage_account_name: martincostellocdnuk
  storage_access_key:
    secure: v3i6Hx1HWq7KJdqSEDvSBH3xwXfCiog7JG1KxI5F+FVGxlFx029ncCh8xs7Qp6Ibg5TW63oQuewCILPtuSR99BJ3+UOiM3yeq4ymU3zMktvBr4IihTqHzmlrF31HYD3W
  container: $root
  artifact: content
  set_content_type: true
  unzip: true
  on:
    branch: deploy
